services: 
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
 
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
  
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'