services: 
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - '5000:6010'
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '3000:8080'